"""Typed ORM models for the FastAPI backend."""

from app.db.models.manager import (
    HostAlertRule,
    HostAlertSettings,
    ManagerCertDeployment,
    ManagerCertificate,
    ManagerActivityLog,
    ManagerEmailChange,
    ManagerEmailTemplate,
    ManagerHost,
    ManagerPasswordReset,
    ManagerPendingRegistration,
    ServerLlmKey,
    ServerMeta,
    SystemSetting,
)
from app.db.models.monitoring import HostAlert, HostMetrics, HostProbeResult
from app.db.models.pterodactyl import (
    ActivityLog,
    ActivityLogSubject,
    Allocation,
    Backup,
    Egg,
    EggVariable,
    Nest,
    PanelNode,
    PteroDatabase,
    PteroDatabaseHost,
    PteroServer,
    PteroUser,
    ServerVariable,
)

__all__ = [
    "ActivityLog",
    "ActivityLogSubject",
    "Allocation",
    "Backup",
    "Egg",
    "EggVariable",
    "HostAlertRule",
    "HostAlertSettings",
    "ManagerCertDeployment",
    "ManagerCertificate",
    "ManagerActivityLog",
    "ManagerEmailChange",
    "ManagerEmailTemplate",
    "ManagerHost",
    "ManagerPasswordReset",
    "ManagerPendingRegistration",
    "Nest",
    "PanelNode",
    "PteroDatabase",
    "PteroDatabaseHost",
    "PteroServer",
    "PteroUser",
    "ServerVariable",
    "ServerLlmKey",
    "ServerMeta",
    "SystemSetting",
]
